(batch jess\\ww.clp)
(deffacts caves
 (worldsize 4 4)
 (wumpus (x 1) (y 3))
 (pit (x 3) (y 1))
 (pit (x 3) (y 3))
 (pit (x 4) (y 4))
 (gold (x 2) (y 3) (amount 10))
 (exit (x 1) (y 1))
 (nocave (x 2) (y 4))
 (hunter (agent Xena)))
;(watch all)
(reset)
(run)
